use std::{
    collections::{HashMap, HashSet},
    fs::{OpenOptions, write},
    io::{Read, Seek, SeekFrom, Write},
    path::{Path, PathBuf},
    sync::Arc,
};

use anyhow::{Context, Result};
use chariot_core::{buildcache::BuildCache, ledger::Ledger, resolve_effective_hashes, store::Store, workdir::WorkDirectoryParent};
use chariot_util::{
    fs::make_path,
    lock::{FileLockKind, open_file_locked},
};
use serde::{Deserialize, Serialize};

const CACHE_SUBDIR_STORE: &str = "store";
const CACHE_SUBDIR_BUILD_CACHE: &str = "builddirs";
const CACHE_SUBDIR_WORKDIRS: &str = "workdirs";
const CACHE_FILENAME_LEDGER: &str = "ledger.db";
const CACHE_FILENAME_STATE: &str = "state.json";
const CACHE_FILENAME_GITIGNORE: &str = ".gitignore";

#[derive(Serialize, Deserialize, PartialEq)]
pub struct InputProfile {
    pub arch: String,
    pub options: HashMap<String, String>,
}

#[derive(Serialize, Deserialize, Default)]
pub struct State {
    pub known_input_profiles: Vec<InputProfile>,
    pub cached_hashes: HashMap<usize, HashSet<(String, u128)>>,
}

impl State {
    pub fn all_cached_hashes(&self) -> HashSet<(String, u128)> {
        self.cached_hashes.values().flatten().cloned().collect()
    }
}

pub struct Cache(PathBuf);

impl Cache {
    pub fn get(path: impl AsRef<Path>) -> Result<Self> {
        make_path(&path).context("Failed to make cache directory")?;

        write(path.as_ref().join(CACHE_FILENAME_GITIGNORE), "# Generated by Chariot\n*").context("Failed to write gitignore")?;

        Ok(Self(path.as_ref().canonicalize().context("Failed to canonicalize cache path")?))
    }

    pub fn open_store(&self) -> Result<Store> {
        Store::get(self.0.join(CACHE_SUBDIR_STORE)).context("Failed to get store")
    }

    pub fn open_ledger(&self) -> Result<Ledger> {
        Ledger::get(self.0.join(CACHE_FILENAME_LEDGER)).context("Failed to get ledger")
    }

    pub fn open_build_cache(&self) -> Result<BuildCache> {
        BuildCache::get(self.0.join(CACHE_SUBDIR_BUILD_CACHE)).context("Failed to get build cache")
    }

    pub fn open_workdir_parent(&self) -> Result<Arc<WorkDirectoryParent>> {
        let workdir_parent = WorkDirectoryParent::get(self.0.join(CACHE_SUBDIR_WORKDIRS)).context("Failed to get workdirs")?;
        Ok(Arc::new(workdir_parent))
    }

    pub fn with_state<T>(&self, func: impl FnOnce(&mut State) -> Result<T>) -> Result<T> {
        let mut state_file = open_file_locked(
            self.0.join(CACHE_FILENAME_STATE),
            OpenOptions::new().create(true).write(true).read(true),
            FileLockKind::Exclusive,
        )
        .context("Failed to open state file")?;

        let mut state_data = String::new();
        state_file.read_to_string(&mut state_data).context("Failed to read state file")?;

        let mut state = if state_data.is_empty() {
            State::default()
        } else {
            serde_json::from_str::<State>(&state_data).context("Failed to parse state file")?
        };

        let result = func(&mut state)?;

        let state_data = serde_json::to_vec(&state).context("Failed to serialize state file")?;
        state_file.seek(SeekFrom::Start(0)).context("Failed to seek state file")?;
        state_file.set_len(state_data.len() as u64).context("Failed to truncate state file")?;
        state_file.write_all(&state_data).context("Failed to write state file")?;

        Ok(result)
    }
}

pub fn prune_store_and_ledger(store: &Store, ledger: &Ledger, live_hashes: &HashSet<(String, u128)>) -> Result<()> {
    let live_refs: HashSet<(&str, u128)> = live_hashes.iter().map(|(cat, hash)| (cat.as_str(), *hash)).collect();
    store
        .prune_store(resolve_effective_hashes(ledger, live_refs.iter().copied())?)
        .context("Failed to prune store")?;
    ledger.prune(live_refs).context("Failed to prune ledger")?;
    Ok(())
}
