use std::{
    collections::HashSet,
    fs::write,
    path::{Path, PathBuf},
    sync::Arc,
};

use anyhow::{Context, Result, bail};
use chariot_core::{buildcache::BuildCache, ledger::Ledger, resolve_effective_hashes, store::Store, workdir::WorkDirectoryParent};
use chariot_util::fs::make_path;

use crate::cache::db::Database;

mod db;
mod state;

pub const CACHE_VERSION: i64 = 1;

const CACHE_SUBDIR_STORE: &str = "store";
const CACHE_SUBDIR_BUILD_CACHE: &str = "builddirs";
const CACHE_SUBDIR_WORKDIRS: &str = "workdirs";
const CACHE_FILENAME_LEDGER: &str = "ledger.db";
const CACHE_FILENAME_GITIGNORE: &str = ".gitignore";
const CACHE_FILENAME_DB: &str = "state.db";
const CACHE_FILENAME_STATE: &str = "state.toml";

pub struct Cache(PathBuf, pub Database);

impl Cache {
    pub fn get(path: impl AsRef<Path>) -> Result<Self> {
        make_path(&path).context("Failed to make cache directory")?;

        let path_state = path.as_ref().join(CACHE_FILENAME_STATE);
        match state::read(&path_state).context("Failed to read cache state")? {
            Some(version) => {
                if version != CACHE_VERSION {
                    bail!(
                        "Chariot cache version mismatch, expected `{}`, got `{}`. This likely means you updated chariot or the cache was generated by a newer version. Quickest resolution is to delete the cache.",
                        CACHE_VERSION,
                        version
                    );
                }
            }
            None => state::write(&path_state, CACHE_VERSION).context("Failed to write cache state")?,
        };

        write(path.as_ref().join(CACHE_FILENAME_GITIGNORE), "# Generated by Chariot\n*").context("Failed to write gitignore")?;

        Ok(Self(
            path.as_ref().canonicalize().context("Failed to canonicalize cache path")?,
            Database::get(path.as_ref().join(CACHE_FILENAME_DB))?,
        ))
    }

    pub fn open_store(&self) -> Result<Store> {
        Store::get(self.0.join(CACHE_SUBDIR_STORE)).context("Failed to get store")
    }

    pub fn open_ledger(&self) -> Result<Ledger> {
        Ledger::get(self.0.join(CACHE_FILENAME_LEDGER)).context("Failed to get ledger")
    }

    pub fn open_build_cache(&self) -> Result<BuildCache> {
        BuildCache::get(self.0.join(CACHE_SUBDIR_BUILD_CACHE)).context("Failed to get build cache")
    }

    pub fn open_workdir_parent(&self) -> Result<Arc<WorkDirectoryParent>> {
        let workdir_parent = WorkDirectoryParent::get(self.0.join(CACHE_SUBDIR_WORKDIRS)).context("Failed to get workdirs")?;
        Ok(Arc::new(workdir_parent))
    }
}

pub fn prune_store_and_ledger(store: &Store, ledger: &Ledger, live_hashes: &HashSet<(String, u128)>) -> Result<()> {
    let live_refs: HashSet<(&str, u128)> = live_hashes.iter().map(|(cat, hash)| (cat.as_str(), *hash)).collect();
    store
        .prune_store(resolve_effective_hashes(ledger, live_refs.iter().copied())?)
        .context("Failed to prune store")?;
    ledger.prune(live_refs).context("Failed to prune ledger")?;
    Ok(())
}
