use std::{
    fs::{self, exists, read_to_string, rename},
    path::Path,
    str::FromStr,
};

use anyhow::{Result, bail};

const STATE_KEY_VERSION: &str = "version";

pub fn read(path: impl AsRef<Path>) -> Result<Option<i64>> {
    if !exists(&path)? {
        return Ok(None);
    }

    let data = read_to_string(&path)?;
    let table = toml::Table::from_str(&data)?;

    let version = match table.get(STATE_KEY_VERSION).and_then(|v| v.as_integer()) {
        None => bail!("Missing or invalid version"),
        Some(version) => version,
    };

    Ok(Some(version))
}

pub fn write(path: impl AsRef<Path>, version: i64) -> Result<()> {
    let mut table = toml::Table::new();
    table.insert(String::from(STATE_KEY_VERSION), toml::Value::Integer(version));

    let data = format!("# Generated by chariot. DONT TOUCH!\n{}", toml::to_string(&table)?);

    let tmp_path = path.as_ref().with_added_extension(".tmp");
    fs::write(&tmp_path, data)?;
    rename(&tmp_path, &path)?;

    Ok(())
}
