use std::{
    fs::write,
    io,
    path::{Path, PathBuf},
};

use anyhow::{Context, Result};
use chariot_config::lua::{EMBEDDED_LUA_FILE_BUILTINS, EMBEDDED_LUA_FILE_HELPERS, EMBEDDED_LUA_FILE_META};
use chariot_util::fs::make_path;
use clap::CommandFactory;
use clap_complete::generate;
use log::info;
use serde_json::json;

use crate::cli::args::{ChariotOptions, SupportCommand};

const LSP_SUPPORT_DIR: &str = ".chariot-lsp-support";

pub fn run(command: SupportCommand) -> Result<()> {
    match command {
        SupportCommand::SetupLSP { support_dir } => setup_lua_lsp(&support_dir),
        SupportCommand::Completions { shell } => {
            generate(shell, &mut ChariotOptions::command(), "chariot".to_string(), &mut io::stdout());
            Ok(())
        }
    }
}

fn setup_lua_lsp(project_dir: &Path) -> Result<()> {
    let lsp_support_dir = PathBuf::from(LSP_SUPPORT_DIR);
    make_path(&lsp_support_dir).context("Failed to make LSP support directory")?;
    for (filename, contents) in [
        ("builtins.lua", EMBEDDED_LUA_FILE_BUILTINS),
        ("helpers.lua", EMBEDDED_LUA_FILE_HELPERS),
        ("meta.lua", EMBEDDED_LUA_FILE_META),
        (".gitignore", "# Generated by Chariot\n*"),
        (
            "README.txt",
            "This directory (and files within) is generated by chariot for lua lsp (LuaLS) integration.\nIt can and will fall out of date over time, at which point it should be re-genereated.\nShould not be committed to git.",
        ),
    ] {
        let filepath = lsp_support_dir.join(filename);
        write(&filepath, contents).with_context(|| format!("Failed to write `{}`", filepath.display()))?;
    }

    write(
        project_dir.join(".luarc.json"),
        serde_json::to_string_pretty(&json!({
            "$schema": "https://raw.githubusercontent.com/LuaLS/vscode-lua/master/setting/schema.json",
            "workspace.library": [LSP_SUPPORT_DIR],
            "workspace.ignoreDir": [".chariot-cache", ".chariot-rootfs"],
            "workspace.useGitIgnore": true,
            "runtime.builtin": {
                "basic": "enable",
                "coroutine": "disable",
                "debug": "disable",
                "io": "disable",
                "math": "enable",
                "os": "disable",
                "package": "enable",
                "string": "enable",
                "table": "enable",
                "utf8": "disable"
            }
        }))?,
    )
    .context("Failed to write .luarc.json")?;

    info!("Generated `.luarc.json` and `{}`", LSP_SUPPORT_DIR);

    Ok(())
}
